### ISSUE TITLE
Examples not rendering

### ISSUE THREAD

**Issue by boyswan** [katharostech/bevy_retrograde#59]
Trying to run an example via: 
`❯ cargo run --features="ldtk" --example ldtk_map`

The window loads but with a black screen. This seems to be the case for all examples (hello_world)
Testing on OSX 10.14.6.

**Comment by zicklag** [comment]
Hey there! Thanks for the report!

Unfortunately Bevy Retrograde doesn't work on OSX yet, but we are actively working on it! Once we can get Bevy's built-in renderer working on OpenGL and WebGL we are going to migrate to using Bevy's built-in renderer, and that _will_ support OSX. You may want to subscribe to #41 which will track progress with our migration to Bevy's renderer.

Let me know if you have any more questions!

**Comment by boyswan** [comment]
Amazing, thanks for the reply!
