### ISSUE TITLE
🐞 Double window on startup (windows 10)

### ISSUE THREAD

**Issue by Bowarc** [katharostech/bevy_retrograde#62]
When i run any program made with bevy_retrograde i have a bug that make a seccond window pop and stay for less than 0.1s while the game's window is loading

https://user-images.githubusercontent.com/63136904/130366924-70a910a5-2825-435e-bdaa-274811b2bf47.mp4

**Comment by zicklag** [comment]
Thanks for the report!

We're currently putting all of our effort into migrating Bevy Retrograde to Bevy's built-in renderer ( #41 ) which could totally change the way the window is loaded and hopefully fix your issue.

Once we finish migrating migrating the renderer I'll come back to this and we'll see if it fixes your issue.
